language: julia

os:
  - linux
  - osx

julia:
  - 1.7
  - 1.8

notifications:
  email: false

# jobs:
#   include:
#     - stage: "docs"
#       julia: 1.7
#       os: linux
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
